name = input("What is your name?" )
print("Hello " + name + ":-)")
input()
color = input("what is your favorite color?" )
print("Not what I would have picked.")
input()
birth_year = input("What year were you born?" )
age = 2024 - int(birth_year)
print("Wow")
input()
print("So, you're " + str(name) +"the " + str(age) + " year old who loves " + color +". Have I got that right?" )
answer = input("Well?")
if answer  "yes" : print("Damn I'm good")
input()
if answer is "Yes" : print("Damn I'm good")
input()
if answer is "no" : print("So you're a liar then")
input()
if answer is "No" : print("Damn I'm good")
input()